name: giyotinfilms
favicon: null
layout_spectrum: 0.013426864985376596
typography_spectrum: 0.9263010721188039
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.1935693514533341
  lightness: 0.1008769164327532
  saturation: 0.8449142349418253
  rhythmicContrast: 0.7490677395835519
purpose: []
