typography_spectrum: 0.84609
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#9f9f9f'
    - '#3f3f3f'
    - '#a12034'
  brandStrength: 0.875
  lightness: 0.1008769164327532
  saturation: 1
  rhythmicContrast: 0
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.56647
analytics:
  google: null
  facebook: null
  twitter: null
name: giyotin films
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: About us
    id: e8a84635-b3bd-4644-a08d-88f8f1216895
    type: content
  - name: Projects
    id: d24ee384-c33a-4a83-9e22-dfe9c8effca7
    type: content
  - name: Upcoming projects
    id: 58321134-690d-47bc-98e4-8a1e493bfc0f
    type: content
favicon: null
purpose: []
